# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    redis_host: '%env(string:REDIS_HOST)%'
    redis_port: '%env(string:REDIS_PORT)%'
    redis_dsn: 'redis://%redis_host%:%redis_port%'

    selenium_host: 'http://chrome:4444/wd/hub'
    screenshot_path: '%kernel.project_dir%/var/screens'

    start_page: 'https://www.kingdoms.com/'
    account_email: '%env(string:EMAIL)%'
    account_pass: '%env(string:PASS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    Predis\Client:
        class: Predis\Client
        autowire: true
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
